  /*
  Auto-generated by: https://github.com/pmndrs/gltfjsx
  */

  import React from 'react'
  import { useGLTF, Html } from '@react-three/drei'
  import WorkDisplay from '../app/inner-display/page' // Adjust this import path to match your project structure!

  const Comp = (props) => {
    const { nodes, materials } = useGLTF('/models/comp-transformed.glb')
    
    return (
      <group {...props} dispose={null}>
        {/* Keyboard Keys */}
        <mesh geometry={nodes.Cube022.geometry} material={materials['Material.075_1001']} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube037.geometry} material={materials['Material.001_1001']} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube038.geometry} material={materials[';_1001']} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube039.geometry} material={materials.tab_1001} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube040.geometry} material={materials.caps_1001} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube041.geometry} material={materials.Shift_1001} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube042.geometry} material={materials.ctrl_2_1001} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube043.geometry} material={materials['Material.007_1001']} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube044.geometry} material={materials.alt_1_1001} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube045.geometry} material={materials.YZ_1001} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube046.geometry} material={materials['Material.010_1001']} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube047.geometry} material={materials['Material.011_1001']} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube048.geometry} material={materials['Material.012_1001']} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube049.geometry} material={materials['Material.014_1001']} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube050.geometry} material={materials['Material.013_1001']} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube052.geometry} material={materials['Material.015_1001']} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube054.geometry} material={materials.F3_1001} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube056.geometry} material={materials.F4_1001} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube058.geometry} material={materials.F5_1001} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube060.geometry} material={materials.F6_1001} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube062.geometry} material={materials.F7_1001} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube064.geometry} material={materials.F8_1001} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube066.geometry} material={materials.F10_1001} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube068.geometry} material={materials.F11_1001} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube070.geometry} material={materials.F12_1001} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube072.geometry} material={materials.Delete_1001} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube074.geometry} material={materials['3_1001']} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube076.geometry} material={materials['4_1001']} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube078.geometry} material={materials['5_1001']} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube080.geometry} material={materials['6_1001']} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube082.geometry} material={materials['7_1001']} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube084.geometry} material={materials['8_1001']} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube086.geometry} material={materials['9_1001']} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube088.geometry} material={materials['0_1001']} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube090.geometry} material={materials['-_1001']} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube092.geometry} material={materials['+_1001']} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube094.geometry} material={materials.Bacspace_1001} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube096.geometry} material={materials.W_1001} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube098.geometry} material={materials.S_1001} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube100.geometry} material={materials.D_1001} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube102.geometry} material={materials.E_1001} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube104.geometry} material={materials.R_1001} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube106.geometry} material={materials.T_1001} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube108.geometry} material={materials.Y_1001} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube110.geometry} material={materials.U_1001} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube112.geometry} material={materials.I_1001} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube114.geometry} material={materials['Material.044_1001']} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube116.geometry} material={materials.P_1001} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube118.geometry} material={materials.ú_1001} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube120.geometry} material={materials['(_1001']} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube122.geometry} material={materials.enter_1001} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube124.geometry} material={materials['←_1001']} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube126.geometry} material={materials.Stop_1001} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube128.geometry} material={materials.ctrl_1_1001} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube130.geometry} material={materials['Material.073_1001']} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube132.geometry} material={materials.ctrl_1001} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube134.geometry} material={materials.alt_1001} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube136.geometry} material={materials.Space_1001} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube138.geometry} material={materials.X_1001} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube140.geometry} material={materials['Material.061_1001']} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube142.geometry} material={materials.V_1001} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube144.geometry} material={materials.B_1001} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube146.geometry} material={materials.N_1001} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube148.geometry} material={materials.F_1001} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube150.geometry} material={materials.G_1001} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube152.geometry} material={materials.H_1001} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube154.geometry} material={materials.J_1001} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube156.geometry} material={materials['Material.055_1001']} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube158.geometry} material={materials.L_1001} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube160.geometry} material={materials['Material.057_1001']} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube162.geometry} material={materials['Material.058_1001']} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube164.geometry} material={materials['Material.068_1001']} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube166.geometry} material={materials['Material.067_1001']} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube168.geometry} material={materials['Material.066_1001']} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        <mesh geometry={nodes.Cube170.geometry} material={materials.M_1001} rotation={[0.675, 0, 0]} scale={[0.044, 0.043, 0.043]} />
        
        {/* Chassis / Frame parts */}
        <mesh geometry={nodes.Cube001.geometry} material={materials.Bok2_1001_1001} scale={[1.337, 1, 1]} />
        <mesh geometry={nodes.Cube002.geometry} material={materials.Bok1_1001_1001} scale={[1.337, 1, 1]} />
        <mesh geometry={nodes.Cube015.geometry} material={materials['Material.004_1001_1001']} />
        <mesh geometry={nodes.Cube018.geometry} material={materials['Material.005_1001_1001']} />
        <mesh geometry={nodes.Cube020.geometry} material={materials['Material.006_1001_1001']} scale={[1.337, 1, 1]} />

  {/* ============================================================= */}
  {/* MONITOR SCREEN */}
  {/* ============================================================= */}
  <group>
    {/* Physical monitor mesh */}
    <mesh
      geometry={nodes.Cube012.geometry}
      material={materials.term_1001}
      scale={[1.337, 1, 1]}
    />

    {/* Interactive Website */}
    <Html
      transform
      occlude
      position={[0, 0.55, 0.055]} // Adjust this until perfectly flush
      rotation={[0, 0, 0]}
      scale={0.5}
      distanceFactor={1}
      zIndexRange={[100, 0]}
      style={{
        width: "1280px",
        height: "800px",
        pointerEvents: "auto",
        userSelect: "none",
      }}
    >
      <iframe
        src="http://localhost:3000/inner-display"
        title="Terminal OS"
        className="w-full h-full border-0 rounded-md"
        style={{
          pointerEvents: "auto",
          background: "#000",
        }}
        allow="fullscreen"
      />
    </Html>
  </group>
      </group>
    )
  }

  useGLTF.preload('/models/comp-transformed.glb')

  export default Comp 