/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 rocket.glb -T 
Files: rocket.glb [14.96MB] > C:\Users\shiva\Desktop\thecrewhousemedia\public\models\rocket-transformed.glb [1.29MB] (91%)
Author: ArgonaTAI (https://sketchfab.com/ArgonaTAI)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rocket-c768ad321b264a939e1f376b585c4b08
Title: Rocket
*/

import React, { memo } from 'react'
import { useGLTF } from '@react-three/drei'

const RocketModel = (props) => {
   const { nodes, materials } = useGLTF('/models/crew-rocket.glb')
   return (
     <group {...props} dispose={null}>
       <mesh geometry={nodes.Circle_0.geometry} material={materials.Rocket} position={[0.493, 1.432, 0]} rotation={[-Math.PI / 2, 0.416, 0]} />
       <mesh geometry={nodes.Circle.geometry} material={materials.Iron} position={[0.493, 1.432, 0]} rotation={[-0.767, 1.024, 2.027]} />
       <mesh geometry={nodes.Circle001_1002.geometry} material={materials.Green_Glass_Glossy} position={[0.493, 1.432, 0]} rotation={[-0.26, -0.481, -0.473]} />
       <mesh geometry={nodes.Cube.geometry} material={materials.Red_GlossyMetal} position={[0.493, 1.432, 0]} rotation={[-0.767, 1.024, 2.027]} />
       <mesh geometry={nodes.Sphere003_0.geometry} material={materials['Sphere.003_0']} position={[0.493, 1.432, 0]} rotation={[-Math.PI / 2, 0, 0]} />
     </group>
   )
 }
 
 useGLTF.preload('/models/crew-rocket.glb')
// Optimization: React.memo prevents the 3D model from re-rendering unnecessarily
export default memo(RocketModel)