/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 rocketmodelfix.glb -T
Files: rocketmodelfix.glb [4.36MB] > C:\Users\shiva\Desktop\Projects\thecrewhousemedia\public\models\rocketmodelfix-transformed.glb [400.89KB] (91%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
const RocketModelFix = (props) => {
  const { nodes, materials } = useGLTF('/models/rocketmodelfix-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Circle_0.geometry} material={materials.Rocket} position={[0.493, 1.432, 0]} rotation={[-Math.PI / 2, 0.416, 0]} />
      <mesh geometry={nodes.Circle.geometry} material={materials.Iron} position={[0.493, 1.432, 0]} rotation={[-0.767, 1.024, 2.027]} />
      <mesh geometry={nodes.Circle001_1002.geometry} material={materials.Green_Glass_Glossy} position={[0.493, 1.432, 0]} rotation={[-0.26, -0.481, -0.473]} />
      <mesh geometry={nodes.Cube.geometry} material={materials.Red_GlossyMetal} position={[0.493, 1.432, 0]} rotation={[-0.767, 1.024, 2.027]} />
      <mesh geometry={nodes.Sphere003_0.geometry} material={materials['Sphere.003_0']} position={[0.493, 1.432, 0]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/rocketmodelfix-transformed.glb')

export default RocketModelFix
